### ISSUE TITLE
Readme request

### ISSUE THREAD

**Issue by bm777** [EricLBuehler/candle-vllm#1]
@EricLBuehler, nice project :)
Can you provide a readme to have an overview of your project?

**Comment by EricLBuehler** [comment]
Hi @bm777, thank you for your interest!

Here is the [overview section](https://github.com/EricLBuehler/candle-vllm#overview). `candle-vllm` is oriented around the model pipeline, and all requests are sent through this model pipeline. It is where the model's inference machinery is implemented (such as sampling and generation).

To add a `t5` model pipeline, you would need to:
 - Implement the `ModulePipeline` trait.
 - Add a simple API to download the model and construct the model (I plan on making this a trait within the day).

Please feel free to contribute!

**Comment by EricLBuehler** [comment]
Thanks, glad that it was helpful!

**Comment by EricLBuehler** [comment]
Closing this now so it does not become stale, but please feel free to reopen!
