### ISSUE TITLE
Pipeline batching tracking issue

### ISSUE THREAD

**Issue by EricLBuehler** [EricLBuehler/candle-vllm#10]
This is the pipeline batching tracking issue.

**Comment by sigma-andex** [comment]
@EricLBuehler are you working on this yet? would be interested in collaborating on it

**Comment by EricLBuehler** [comment]
That sounds great! Perhaps you can open a PR to track development?

I will be probably making some major changes in the architecture of the `ModulePipeline` in the coming days, but once they are made I will let you know.

**Comment by EricLBuehler** [comment]
Closing this pending a rewrite of the scheduler and cache, see the [scheduler](https://github.com/EricLBuehler/candle-vllm/tree/scheduler) branch. This task is encompassed by the scheduler, which manages the batching. A new tracking issue will be opened.
