### ISSUE TITLE
mistral error

### ISSUE THREAD

**Issue by lambdaofgod** [EricLBuehler/candle-vllm#12]
I've ran the example with model `mistral` but when I try to run the script second time I get

```
openai.InternalServerError: Error: shape mismatch in broadcast_add, lhs: [1, 32, 62, 189], rhs: [1, 1, 62, 62]
```

I've seen this error before when I tried to use candle's LLM on a list of inputs. I think it's the issue with candle's mutability. Did you solve it for LLaMa? I couldn't test it since I don't have access to LLaMa on huggingface (my request for access is pending)

**Comment by EricLBuehler** [comment]
This is a problem with the KV cache. 
> https://github.com/EricLBuehler/candle-vllm/blob/a6c3ec308f05d546be9de61835e83b313537f7a9/src/openai/models/mistral.rs#L176

You are correct that this is a problem relating to Candle's mutability. I have previously fixed this problem with the `llama` pipeline by adding a `clear_cache` method, and that fix should resolve this.

**Comment by EricLBuehler** [comment]
Great!
