### ISSUE TITLE
Support streaming of tokens

### ISSUE THREAD

**Issue by michaelfeil** [EricLBuehler/candle-vllm#2]
I noticed that OpenAI's `stream=True` could be perhaps implemented here:

https://github.com/EricLBuehler/candle-vllm/blob/bc31515011147bea52f854f411627f21e6261a1f/src/openai/pipelines/llama.rs#L248-L260

**Comment by EricLBuehler** [comment]
Hi michaelfei, thanks for pointing that out. I plan on implementing this feature shortly!
