### ISSUE TITLE
[Request] Constrained Generation

### ISSUE THREAD

**Issue by scottwey** [EricLBuehler/candle-vllm#26]
Given the current structure of `candle-vllm`, how difficult would it be to add constrained generation, similar to [lm-format-enforcer](https://github.com/noamgat/lm-format-enforcer/)?

I'm happy to help here however I can.

**Comment by scottwey** [comment]
@EricLBuehler I will try to take a crack at this as soon as I get some time. Thank you for the guidance. :)

**Comment by EricLBuehler** [comment]
@scottwey, I am currently working on [mistral.rs](https://github.com/EricLBuehler/mistral.rs). It has a simpler sampling API and overall file structure, so perhaps you could take a look there? Feel free to raise an issue for further guidance.
