### ISSUE TITLE
Support Mixtral-8x7B-v0.1

### ISSUE THREAD

**Issue by ivanbaldo** [EricLBuehler/candle-vllm#33]
Currently the best open model so maybe worth incorporating as soon as some other stuff gets a bit more completed and stabilized in the project.

**Comment by EricLBuehler** [comment]
Yes, I plan to add one as soon as this is stabilized. [Here](https://github.com/huggingface/candle/blob/main/candle-transformers/src/models/mixtral.rs) is the Candle implementation, for future reference.

**Comment by EricLBuehler** [comment]
`mistral.rs` has an implementation, closing.
