### ISSUE TITLE
candle-vllm build issue

### ISSUE THREAD

**Issue by tupleleap** [EricLBuehler/candle-vllm#35]
I have followed readme document, on ubuntu 23.10 hitting at this build issue, please help me on this

errors detected in the compilation of "kernels/flash_fwd_hdim256_bf16_sm80.cu".
--error 0x1 --

thread '' panicked bindgen_cuda-0.1.4/src/lib.rs:262:21:
nvcc error while executing compiling: "nvcc" "--gpu-architecture=sm_75" "-c" "-o" "/home/tantrajya/Documents/rustprojects/candle-vllm-master/target/release/build/candle-flash-attn-f1535da02b90d1cc/out/flash_fwd_hdim256_bf16_sm80-21dd0f7dd998e506.o" "--default-stream" "per-thread" "-std=c++17" "-O3" "-U__CUDA_NO_HALF_OPERATORS__" "-U__CUDA_NO_HALF_CONVERSIONS__" "-U__CUDA_NO_HALF2_OPERATORS__" "-U__CUDA_NO_BFLOAT16_CONVERSIONS__" "-Icutlass/include" "--expt-relaxed-constexpr" "--expt-extended-lambda" "--use_fast_math" "--verbose" "kernels/flash_fwd_hdim256_bf16_sm80.cu"

**Comment by EricLBuehler** [comment]
Please see #25, this was a Candle bug.
