### ISSUE TITLE
Can the architectural design be improved?

### ISSUE THREAD

**Issue by mokeyish** [EricLBuehler/candle-vllm#4]
Thanks for your `candle-vllm`.

I have my own LLM and tokenizer with diffrent prompt generation, and I want to make it serve as OpenAI compatiable API. I also don't want to modify the code of `candle-vllm`, want just use it as a library.

But now，looking at your design, it seems like you want to do everything by yourself.
https://github.com/EricLBuehler/candle-vllm/blob/cbfd463d72709ab70a360d07cc17be543e56ebd2/src/openai/conversation.rs#L16-L20

I wonder if model, tokenizer and prompt generation can be abstracted into `trait`s?

**Comment by mokeyish** [comment]
The prompt here cannot generate prompt text first and then encode it into token, the results are diffrent.

https://huggingface.co/Qwen/Qwen-7B-Chat/blob/main/qwen_generation_utils.py#L119

**Comment by EricLBuehler** [comment]
Hi @mokeyish, thanks for the idea! Currently, I use a `ModulePipeline` trait for the model, and a `TokenizerWrapper` trait for the tokenizer.

However, the idea of abstracting prompt generation into a trait seems like a great idea! Do you want to contribute this?

**Comment by mokeyish** [comment]
@EricLBuehler Of course, but I don’t necessarily have time. My main job now is to port the pytorch model to candle. It may take some time.

**Comment by EricLBuehler** [comment]
@mokeyish, thanks for the idea! I have added this feature now - please let me know if it is what you had in mind.

**Comment by mokeyish** [comment]
@EricLBuehler Great, so efficient. But still have another issue, Some model cannot generate prompt text first and then encode it into token。

Please look at following example:

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('THUDM/chatglm3-6b', trust_remote_code=True)

input_ids = tokenizer.build_chat_input("Hi, what's your name?")["input_ids"][0].tolist()

prompt_text = tokenizer.decode(input_ids)

input_ids2 = tokenizer.encode(prompt_text)

assert len(input_ids2) == len(input_ids)

```

**Comment by EricLBuehler** [comment]
@mokeyish, just to clarify: it looks like your example shows prompt generation, then tokenization. Am I misunderstanding?

**Comment by mokeyish** [comment]
`input_ids2` and `input_ids` are different. The offcial model use `input_ids` as the model input. I see that you use string prompt in `candle-vllm` 

https://github.com/EricLBuehler/candle-vllm/blob/ac41903e6155e66de45bb5936798a99d4aef035e/src/openai/openai_server.rs#L141

It means we will use `input_ids2` as model input.

**Comment by mokeyish** [comment]
The value of `input_ids` and `input_ids2`:

- input_ids 
   
  [64790, 64792, 64795, 30910, 13, 8686, 30932, 658, 30953, 30917, 475, 1462, 30987, 64796]

- input_ids2 
  [64790, 64792, 790, 30927, 30944, 2080, 30984, 30996, 30917, 404, 31002, 31007, 4865, 31007, 30994, 30910, 13, 8686, 30932, 658, 30953, 30917, 475, 1462, 30987, 31002, 31007, 530, 18971, 31007, 30994]

**Comment by EricLBuehler** [comment]
> `input_ids2` and `input_ids` are different. The offcial model use `input_ids` as model input. I see that you use string prompt in `candle-vllm`
> 
> https://github.com/EricLBuehler/candle-vllm/blob/ac41903e6155e66de45bb5936798a99d4aef035e/src/openai/openai_server.rs#L141
> 
> It means we will use `input_ids2` as model input.

Do you mean the Conversation should take Tensors?
