### ISSUE TITLE
LongRope support for Phi 3

### ISSUE THREAD

**Issue by EricLBuehler** [EricLBuehler/candle-vllm#47]
Reference implementation: https://github.com/EricLBuehler/mistral.rs/blob/master/mistralrs-core/src/layers.rs#L69

**Comment by guoqingbao** [comment]
> Reference implementation: https://github.com/EricLBuehler/mistral.rs/blob/master/mistralrs-core/src/layers.rs#L69

Supported, please refer to latest updates.

**Comment by EricLBuehler** [comment]
Thank you, that looks great. Implemented in #46.
