### ISSUE TITLE
model download failing from HF

### ISSUE THREAD

**Issue by Ranganaths** [EricLBuehler/candle-vllm#59]
I have been getting Error: APIError { data: "request error: Bad Header: invalid header 'Authorization: Bearer hf_XXXXXXX\n'"}

* I have tried and refreshed my token on HF
* i have also made sure i have access to the models

however it still dont work, one think i suspect is that along with token \n is getting appended.. is that a bug ? please let know..

thank you

**Comment by EricLBuehler** [comment]
@Ranganaths I just merged #60 which should fix this!
