### ISSUE TITLE
OpenAI API version

### ISSUE THREAD

**Issue by lambdaofgod** [EricLBuehler/candle-vllm#7]
What version did you use for Python OpenAI package? I've tried with 0.27.8 and I can't even run the example, and after I changed code according to OpenAI pypi page

```
import openai

# Run: HF_TOKEN=... cargo run --release -- --hf-token HF_TOKEN --port 2000 llama7b --repeat-last-n 64


openai.api_base = "http://localhost:2000/v1/"
openai.api_key = ""

completion = openai.ChatCompletion.create(
    model="mistral7b",
    messages=[
        {
            "role": "user",
            "content": "Explain how to best learn Rust.",
        },
    ],
    max_tokens=32,
)
print(completion.choices[0].message.content)
```

I get

> Traceback (most recent call last):
>   File "/home/kuba/.pyenv/versions/3.10.6/lib/python3.10/site-packages/openai/api_requestor.py", line 753, in _interpret_response_line
>     data = json.loads(rbody)
>   File "/home/kuba/.pyenv/versions/3.10.6/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/home/kuba/.pyenv/versions/3.10.6/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/home/kuba/.pyenv/versions/3.10.6/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/kuba/Projects/forks/candle-vllm/examples/llama.py", line 9, in <module>
>     completion = openai.ChatCompletion.create(
>   File "/home/kuba/.pyenv/versions/3.10.6/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
>     return super().create(*args, **kwargs)
>   File "/home/kuba/.pyenv/versions/3.10.6/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
>     response, _, api_key = requestor.request(
>   File "/home/kuba/.pyenv/versions/3.10.6/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
>     resp, got_stream = self._interpret_response(result, stream)
>   File "/home/kuba/.pyenv/versions/3.10.6/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
>     self._interpret_response_line(
>   File "/home/kuba/.pyenv/versions/3.10.6/lib/python3.10/site-packages/openai/api_requestor.py", line 755, in _interpret_response_line
>     raise error.APIError(
> openai.error.APIError: HTTP code 404 from API ()

**Comment by EricLBuehler** [comment]
It looks like I have the `1.3.5` version on my system. Please see #8 for why Mistral is not loading.

After updating `openai`, could you confirm that the `llama` pipeline successfully runs? The `mistral` pipeline should not work because it is not loading the model - although that is seperate from this issue.

**Comment by EricLBuehler** [comment]
#8 is now closed, as such the `mistral` pipeline should also work.

**Comment by lambdaofgod** [comment]
Yup
